# Site settings
author: Tania
title: Infinite Loops for the Very First Time
header-img: img/home-bg.png
email: tanwhiting@aol.com
copyright_name: Tania
description: > # this means to ignore newlines until "baseurl:"
  Potentially Recursive?
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  TaniaWhiting

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
